apiVersion: v1
kind: Service
metadata:
  name: discounts
  labels:
    {{- include "restauranty.labels" . | nindent 4 }}
spec:
  selector:
    app: discounts
  ports:
    - port: 3002
      targetPort: 3002
