apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    {{- include "restauranty.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.client }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghcr.io/{{ .Values.image.owner }}/restauranty-client:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
